# Generated by Django 5.0.6 on 2024-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
