# Generated by Django 5.0.6 on 2024-06-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='place',
        ),
    ]
